export const mealType = [
    'Breakfast',
    'Lunch',
    'Dinner',
    'Snack',
    'Tea Time'
];
export const dishType = [
    'Biscuits and cookies',
    'Breab',
    'Cereals',
    'Condiments and Sauces',
    'Desserts',
    'Drinks',
    'Main Course',
    'Pancake',
    'Preps',
    'Preserve',
    'Salad',
    'Sandwiches',
    'Side dishes',
    'Soup',
    'Starter',
    'Sweets'
];
export const diet = [
    'Alcohol-free',
    'Balanced',
    'High-Fiber',
    'High-Protein',
    'Keto',
    'Kidney friendly',
    'Kocher',
    'Low-Carb',
    'Low-Fat',
    'Low potassium',
    'Low-Sodium',
    'No oil added',
    'No-sugar',
    'Paleo',
    'Pescatarian',
    'Pork-free',
    'Red meat-free',
    'Sugar-conscious',
    'Vegan',
    'Vegetarian'
];
export const cuisineType = [
    'American',
    'Asian',
    'British',
    'Caribbean',
    'Central Europe',
    'Chinese',
    'Eastern Europe',
    'French',
    'Indian',
    'Italian',
    'Japanese',
    'Kocher',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'South American',
    'South East Asia'
];
export const health = [
    "Alcohol-Cocktail",
    "Alcohol-Free",
    "Celery-Free",
    "Crustcean-Free",
    "Dairy-Free",
    "DASH",
    "Egg-Free",
    "Fish-Free",
    "FODMAP-Free",
    "Gluten-Free",
    "Immuno-Supportive",
    "Keto-Friendly",
    "Kidney-Friendly",
    "Kosher",
    "Low Potassium",
    "Low Sugar",
    "Lupine-Free",
    "Mediterranean",
    "Mollusk-Free",
    "Mustard-Free",
    "No oil added",
    "Paleo",
    "Peanut-Free",
    "Pescatarian",
    "Pork-Free",
    "Red-Meat-Free",
    "Sesame-Free",
    "Shellfish-Free",
    "Soy-Free",
    "Sugar-Conscious",
    "Sulfite-Free",
    "Tree-Nut-Free",
    "Vegan",
    "Vegetarian",
    "Wheat-Free"
];